In [ ]:
import pandas as pd
bikes = pd.read_csv('BikeData.csv')
bikes.head()

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
0,01/12/2017,0,-5.2,37,2.2,0.0,0.0,Winter,No Holiday,Yes,207,50
1,01/12/2017,1,-5.5,38,0.8,0.0,0.0,Winter,No Holiday,Yes,139,80
2,01/12/2017,2,-6.0,39,1.0,0.0,0.0,Winter,No Holiday,Yes,22,140
3,01/12/2017,3,-6.2,40,0.9,0.0,0.0,Winter,No Holiday,Yes,43,105
4,01/12/2017,4,-6.0,36,2.3,0.0,0.0,Winter,No Holiday,Yes,59,38

In [ ]:
bikes.columns

Index(['Date', 'Hour', 'Temperature', 'Humidity', 'Wind speed', 'Rainfall',
       'Snowfall', 'Seasons', 'Holiday', 'Functioning Day', 'Partner 1',
       'Partner 2'],
      dtype='object')

In [ ]:
bikes.shape

(8760, 12)

In [ ]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8760 non-null   object
 1   Hour             8760 non-null   int64
 2   Temperature      8581 non-null   float64
 3   Humidity         8760 non-null   int64
 4   Wind speed       8760 non-null   float64
 5   Rainfall         8760 non-null   float64
 6   Snowfall         8760 non-null   float64
 7   Seasons          8760 non-null   object
 8   Holiday          8760 non-null   object
 9   Functioning Day  8760 non-null   object
 10  Partner 1        8760 non-null   int64
 11  Partner 2        8760 non-null   int64
dtypes: float64(4), int64(4), object(4)
memory usage: 821.4+ KB

In [ ]:
bikes["Hour"]

0        0
1        1
2        2
3        3
4        4
        ..
8755    19
8756    20
8757    21
8758    22
8759    23
Name: Hour, Length: 8760, dtype: int64

In [ ]:
bikes['Hour'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
bikes['Seasons'].unique()

array(['Winter', 'Spring', 'Summer', 'Autumn'], dtype=object)

In [ ]:
bikes[['Partner 1', 'Partner 2']]

      Partner 1  Partner 2
0           207         50
1           139         80
2            22        140
3            43        105
4            59         38
...         ...        ...
8755        467        177
8756        296         63
8757        571        665
8758        171        457
8759        442        401

[8760 rows x 2 columns]

In [ ]:
bikes.iloc[278]

Date               12/12/2017
Hour                       14
Temperature              -5.4
Humidity                   32
Wind speed                2.0
Rainfall                  0.0
Snowfall                  0.0
Seasons                Winter
Holiday            No Holiday
Functioning Day           Yes
Partner 1                  96
Partner 2                 205
Name: 278, dtype: object

In [ ]:
bikes.iloc[2467]['Date']

'13/03/2018'

In [ ]:
bikes[~((bikes['Seasons'] == 'Spring') & (bikes['Temperature'] >= 26))].shape

(8733, 12)

In [ ]:
bikes[bikes['Temperature'].isna()]

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
39,02/12/2017,15,NaN,41,2.3,0.0,0.0,Winter,No Holiday,Yes,490,198
50,03/12/2017,2,NaN,79,1.4,0.0,0.0,Winter,No Holiday,Yes,208,54
64,03/12/2017,16,NaN,77,1.6,0.0,0.0,Winter,No Holiday,Yes,49,528
105,05/12/2017,9,NaN,31,1.3,0.0,0.0,Winter,No Holiday,Yes,78,235
151,07/12/2017,7,NaN,93,0.5,0.0,0.9,Winter,No Holiday,Yes,140,129
...,...,...,...,...,...,...,...,...,...,...,...,...
8669,27/11/2018,5,NaN,84,0.6,0.0,0.0,Autumn,No Holiday,Yes,118,58
8679,27/11/2018,15,NaN,70,2.1,0.0,0.0,Autumn,No Holiday,Yes,391,279
8710,28/11/2018,22,NaN,34,1.3,0.0,0.0,Autumn,No Holiday,Yes,476,558
8717,29/11/2018,5,NaN,34,0.9,0.0,0.0,Autumn,No Holiday,Yes,17,13
8742,30/11/2018,6,NaN,68,0.8,0.0,0.0,Autumn,No Holiday,Yes,11,155

In [ ]:
bikes[bikes['Seasons'].isin(['Winter', 'Summer'])].shape

(4368, 12)

In [ ]:
bikes[bikes['Temperature'].isin(range(19, 28))]

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
2870,30/03/2018,14,21.0,28,2.8,0.0,0.0,Spring,No Holiday,Yes,502,467
2942,02/04/2018,14,23.0,42,3.4,0.0,0.0,Spring,No Holiday,Yes,323,676
2944,02/04/2018,16,23.0,47,4.1,0.0,0.0,Spring,No Holiday,Yes,58,1147
2945,02/04/2018,17,22.0,49,3.7,0.0,0.0,Spring,No Holiday,Yes,681,650
2963,03/04/2018,11,19.0,67,1.9,0.0,0.0,Spring,No Holiday,Yes,465,660
...,...,...,...,...,...,...,...,...,...,...,...,...
7644,15/10/2018,12,19.0,60,1.8,0.0,0.0,Autumn,No Holiday,Yes,614,622
7646,15/10/2018,14,20.0,48,2.1,0.0,0.0,Autumn,No Holiday,Yes,187,363
7719,18/10/2018,15,19.0,38,1.9,0.0,0.0,Autumn,No Holiday,Yes,661,428
7766,20/10/2018,14,20.0,22,1.6,0.0,0.0,Autumn,No Holiday,Yes,663,1628
8127,04/11/2018,15,19.0,25,2.1,0.0,0.0,Autumn,No Holiday,Yes,246,594

In [ ]:
bikes['Temperature'].sort_values(ascending=False)

5848    39.4
5847    39.3
5849    39.0
5846    38.7
5825    38.0
        ...
8669     NaN
8679     NaN
8710     NaN
8717     NaN
8742     NaN
Name: Temperature, Length: 8760, dtype: float64

In [ ]:
!pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)

In [ ]:
import requests
r = requests.get("http://example.com")
print(r.text)

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>

In [ ]:
bikes.sort_values(by=['Temperature'], ascending=False)

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
5848,01/08/2018,16,39.4,39,2.5,0.0,0.0,Summer,No Holiday,Yes,76,126
5847,01/08/2018,15,39.3,37,2.3,0.0,0.0,Summer,No Holiday,Yes,401,441
5849,01/08/2018,17,39.0,41,2.6,0.0,0.0,Summer,No Holiday,Yes,298,554
5846,01/08/2018,14,38.7,38,2.4,0.0,0.0,Summer,No Holiday,Yes,158,96
5825,31/07/2018,17,38.0,36,1.3,0.0,0.0,Summer,No Holiday,Yes,320,147
...,...,...,...,...,...,...,...,...,...,...,...,...
8669,27/11/2018,5,NaN,84,0.6,0.0,0.0,Autumn,No Holiday,Yes,118,58
8679,27/11/2018,15,NaN,70,2.1,0.0,0.0,Autumn,No Holiday,Yes,391,279
8710,28/11/2018,22,NaN,34,1.3,0.0,0.0,Autumn,No Holiday,Yes,476,558
8717,29/11/2018,5,NaN,34,0.9,0.0,0.0,Autumn,No Holiday,Yes,17,13
8742,30/11/2018,6,NaN,68,0.8,0.0,0.0,Autumn,No Holiday,Yes,11,155

In [ ]:
bikes.sort_values(by=['Temperature', 'Humidity'], ascending=[True, False])

,Date,Hour,Temperature,Humidity,Wind speed,Rainfall,Snowfall,Seasons,Holiday,Functioning Day,Partner 1,Partner 2
1352,26/01/2018,8,-17.8,40,2.5,0.0,0.5,Winter,No Holiday,Yes,235,288
1351,26/01/2018,7,-17.5,38,3.4,0.0,0.5,Winter,No Holiday,Yes,93,31
1353,26/01/2018,9,-17.5,37,3.8,0.0,0.5,Winter,No Holiday,Yes,76,26
1350,26/01/2018,6,-17.4,40,1.6,0.0,0.5,Winter,No Holiday,Yes,33,18
1349,26/01/2018,5,-16.9,38,2.3,0.0,0.5,Winter,No Holiday,Yes,35,21
...,...,...,...,...,...,...,...,...,...,...,...,...
1238,21/01/2018,14,NaN,18,1.2,0.0,0.0,Winter,No Holiday,Yes,119,100
1910,18/02/2018,14,NaN,17,1.8,0.0,0.0,Winter,No Holiday,Yes,7,162
1886,17/02/2018,14,NaN,15,4.0,0.0,0.0,Winter,Holiday,Yes,0,58
3400,21/04/2018,16,NaN,13,3.3,0.0,0.0,Spring,No Holiday,Yes,1649,560
4276,28/05/2018,4,NaN,0,0.4,0.0,0.0,Spring,No Holiday,Yes,51,58