In [ ]:
import pandas as pd
X = [13, 21, 30, 65, 50]
Y = [200, 90, 10, 83, 12]
X1 = pd.Series(X)
Y1 = pd.Series(Y)
X1, Y1

(0    13
 1    21
 2    30
 3    65
 4    50
 dtype: int64, 0    200
 1     90
 2     10
 3     83
 4     12
 dtype: int64)

In [ ]:
new_table = pd.concat([X1, Y1], axis=1)
new_table.columns = ['X1', 'Y1']
new_table

   X1   Y1
0  13  200
1  21   90
2  30   10
3  65   83
4  50   12

In [ ]:
new_table['X1'].corr(new_table['Y1'])

-0.5065445406508795

In [ ]:
new_table = new_table.rename(columns={'X1': 'Критерий 1', 'Y1': 'Критерий 2'})
new_table

   Критерий 1  Критерий 2
0          13         200
1          21          90
2          30          10
3          65          83
4          50          12

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
pd.DataFrame({'list1':list1, 'list2':list2, 'list3':list3})

   list1  list2  list3
0      1      5      9
1      2      6     10
2      3      7     11
3      4      8     12

In [ ]:
import numpy as np
np.corrcoef([13, 21, 30, 65, 50], [200, 90, 10, 83, 12])

array([[ 1.        , -0.50654454],
       [-0.50654454,  1.        ]])

In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.listdir()

['.config', 'sample_data']

In [ ]:
Scrab = pd.read_csv('ScrabbleGames.csv')
Scrab

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
0,451519,1590,0,38,Matt Laufer,0,1892,1877,5,608,Pam Grazette,0,1712,1692,14,1,1,1994-03-11,0,1994
1,451520,1590,0,38,Matt Laufer,0,1892,1877,5,82,Sally Ricketts,0,1390,1347,36,3,1,1994-03-11,0,1994
2,451521,1590,0,38,Matt Laufer,0,1892,1877,5,4001,James Guillot,0,1712,1700,22,5,1,1994-03-11,0,1994
3,451522,1590,0,38,Matt Laufer,0,1892,1877,5,5676,Rhoda Squires,0,1642,1591,29,8,1,1994-03-11,0,1994
4,451523,1590,0,38,Matt Laufer,0,1892,1877,5,4001,James Guillot,0,1712,1700,22,9,1,1994-03-11,0,1994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37461,1823779,3021,0,15830,Ella Bartholomew,0,0,923,21,2750,Poppy Thompson,0,0,771,30,6,3,1994-09-17,0,1994
37462,1823780,3021,0,1859,Claire Ullman,0,730,756,23,2750,Poppy Thompson,0,0,771,30,8,3,1994-09-17,0,1994
37463,1823781,3021,0,2750,Poppy Thompson,0,0,771,30,6345,Myra Odess,0,1150,1111,16,2,3,1994-09-17,0,1994
37464,1823782,3021,0,2750,Poppy Thompson,0,0,771,30,2441,Avis Turner,0,739,724,27,3,3,1994-09-17,0,1994
37465,1823783,3021,0,2750,Poppy Thompson,0,0,771,30,4226,Lois Molitors,0,0,510,32,11,3,1994-09-17,0,1994

In [24]:
Scrab.groupby('tourneyid')['winnerscore'].mean().corr(Scrab.groupby('tourneyid')['winnernewrating'].mean())

-0.6040132147335744

In [23]:
winnerscore1 = Scrab.groupby('tourneyid')['winnerscore'].mean()
winnernewrating1 = Scrab.groupby('tourneyid')['winnernewrating'].mean()
new_table = pd.concat([winnerscore1, winnernewrating1], axis=1)
new_table

           winnerscore  winnernewrating
tourneyid
1524          0.000000      1607.119701
1590          0.000000      1446.150134
1591          4.287538      1459.314096
1592          0.000000      1384.846262
1593          0.000000      1115.964246
...                ...              ...
4380          0.000000      1440.960177
4381          0.000000      1497.285714
5465          0.000000      1143.500000
5677          0.000000      1044.817460
5678          0.000000      1109.714286

[119 rows x 2 columns]

In [25]:
new_table['winnernewrating'].corr(new_table['winnerscore'])

-0.6040132147335744

In [26]:
Scrab.groupby('tourneyid')['winnerscore'].mean().corr(Scrab.groupby('tourneyid')['loserscore'].mean())

0.9999382016001124

In [27]:
Scrab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37466 entries, 0 to 37465
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gameid           37466 non-null  int64
 1   tourneyid        37466 non-null  int64
 2   tie              37466 non-null  int64
 3   winnerid         37466 non-null  int64
 4   winnername       37466 non-null  object
 5   winnerscore      37466 non-null  int64
 6   winneroldrating  37466 non-null  int64
 7   winnernewrating  37466 non-null  int64
 8   winnerpos        37466 non-null  int64
 9   loserid          37466 non-null  int64
 10  losername        37466 non-null  object
 11  loserscore       37466 non-null  int64
 12  loseroldrating   37466 non-null  int64
 13  losernewrating   37466 non-null  int64
 14  loserpos         37466 non-null  int64
 15  round            37466 non-null  int64
 16  division         37466 non-null  int64
 17  date             37466 non-null  object
 18  lexicon          37466 non-null  int64
 19  year             37466 non-null  int64
dtypes: int64(17), object(3)
memory usage: 5.7+ MB

In [28]:
Scrab.groupby('tourneyid')['winnernewrating'].mean().corr(Scrab.groupby('tourneyid')['losernewrating'].mean())

0.9783569191327567

In [29]:
Scrab_1 = Scrab[Scrab['round'] == 1]
Scrab_1.head()

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
0,451519,1590,0,38,Matt Laufer,0,1892,1877,5,608,Pam Grazette,0,1712,1692,14,1,1,1994-03-11,0,1994
15,451534,1590,0,47,Joe Weinike,0,1954,1961,3,10779,John E Meyers,0,1717,1675,28,1,1,1994-03-11,0,1994
24,451543,1590,0,54,Rose Kreiswirth,0,1842,1844,7,134,Nancy Okolsky,0,1345,1375,33,1,1,1994-03-11,0,1994
32,451551,1590,0,58,Sal Piro,0,1592,1566,23,4435,Jerry Mory,0,1340,1357,30,1,1,1994-03-11,0,1994
37,451556,1590,0,59,Marjorie Schoneboom,0,1880,1878,4,4001,James Guillot,0,1712,1700,22,1,1,1994-03-11,0,1994

In [34]:
Scrab_1.groupby('tourneyid')['winnerscore'].mean().corr(Scrab_1.groupby('tourneyid')['loserscore'].mean())

0.9998969144453593

In [36]:
Scrab.groupby('tourneyid')['winnernewrating'].mean().corr(Scrab.groupby('tourneyid')['losernewrating'].mean())

0.9783569191327567

In [37]:
Scrab_1 = Scrab[Scrab['tie'] == 0]

In [38]:
Scrab_1.groupby('tourneyid')['winnernewrating'].mean().corr(Scrab_1.groupby('tourneyid')['losernewrating'].mean())

0.9782555275896676

In [39]:
Scrab_2 = Scrab[Scrab['tie'] == 1]

In [40]:
Scrab_2.groupby('tourneyid')['winnernewrating'].mean().corr(Scrab_2.groupby('tourneyid')['losernewrating'].mean())

0.9233027219958259

In [41]:
Scrab['tie'].unique()

array([0, 1])

In [42]:
Scrab['winnername'].value_counts()

Lester Schonbrun     127
Joel Sherman         126
Patricia Barrett     124
Rose Kreiswirth      119
Stuart Goldman       117
                    ...
Dennis Tostowaryk      1
Lee Martin             1
Jim Yee                1
Irma Triggs            1
Margaret Melito        1
Name: winnername, Length: 2166, dtype: int64

In [45]:
Scrab_3 = Scrab[Scrab['winnername'] == 'Lester Schonbrun']
Scrab_3

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
644,452163,1591,0,727,Lester Schonbrun,0,1982,1970,7,454,Mary Rhoades,0,1720,1610,53,1,1,1994-07-07,0,1994
645,452164,1591,0,727,Lester Schonbrun,0,1982,1970,7,3429,Craig Atterbury,0,1779,1769,43,2,1,1994-07-07,0,1994
646,452165,1591,0,727,Lester Schonbrun,0,1982,1970,7,2095,Helaine Garren,0,1645,1707,32,5,1,1994-07-07,0,1994
647,452166,1591,0,727,Lester Schonbrun,0,1982,1970,7,299,Steve Polatnick,0,2031,2014,8,6,1,1994-07-07,0,1994
648,452167,1591,0,727,Lester Schonbrun,443,1982,1970,7,1525,Jim Kramer,370,1985,1956,13,9,1,1994-07-07,0,1994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16764,707136,2970,0,727,Lester Schonbrun,0,1936,1937,15,1489,John Luebkemann,0,1905,1850,22,14,1,1994-03-25,0,1994
16766,707138,2970,0,727,Lester Schonbrun,0,1936,1937,15,1974,Bob Lipton,0,1996,2003,1,17,1,1994-03-25,0,1994
16767,707139,2970,0,727,Lester Schonbrun,439,1936,1937,15,586,Robert Linn,320,1806,1832,3,18,1,1994-03-25,0,1994
30525,1437035,3045,0,727,Lester Schonbrun,0,1988,2005,2,3430,Ruth Sparer Stern,0,1851,1781,31,8,1,1994-12-02,0,1994
30526,1437036,3045,0,727,Lester Schonbrun,0,1988,2005,2,53,Joel Sherman,0,2004,2033,1,15,1,1994-12-02,0,1994

In [44]:
Scrab_3.groupby('tourneyid')['winnerscore'].mean().corr(Scrab_3.groupby('tourneyid')['winneroldrating'].mean())

0.052293839839737934

In [48]:
Scrab_4 = Scrab[Scrab['winnername'] == 'Stuart Goldman']
Scrab_4.head()

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
443,451962,1591,0,238,Stuart Goldman,0,1883,1830,28,2404,Kathleen Watson,0,1746,1709,47,4,1,1994-07-07,0,1994
444,451963,1591,0,238,Stuart Goldman,0,1883,1830,28,7473,Merle Merrick,0,1700,1700,42,6,1,1994-07-07,0,1994
445,451964,1591,0,238,Stuart Goldman,0,1883,1830,28,2095,Helaine Garren,0,1645,1707,32,8,1,1994-07-07,0,1994
446,451965,1591,0,238,Stuart Goldman,0,1883,1830,28,3,Rick Wong,0,1862,1848,27,10,1,1994-07-07,0,1994
447,451966,1591,0,238,Stuart Goldman,0,1883,1830,28,669,Carol Kaplan,0,1709,1703,45,14,1,1994-07-07,0,1994

In [49]:
Scrab_4.groupby('tourneyid')['winnerscore'].mean().corr(Scrab_4.groupby('tourneyid')['winneroldrating'].mean())

-0.4985311528143817

In [51]:
Scrab_5 = Scrab[Scrab['tourneyid'] == 4376]
Scrab_5.head()

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
17895,787911,4376,0,2590,Raymond Slaughter,397,1180,0,14,1489,John Luebkemann,326,1875,0,2,1,1,1994-07-02,0,1994
17896,787912,4376,0,1489,John Luebkemann,318,1875,0,2,1579,Marcia Wade,315,1689,0,12,2,1,1994-07-02,0,1994
17897,787913,4376,0,4884,Paul Erland,428,1847,0,5,1489,John Luebkemann,330,1875,0,2,3,1,1994-07-02,0,1994
17898,787914,4376,0,1489,John Luebkemann,366,1875,0,2,2431,Mark Edward Owens,362,1946,0,8,4,1,1994-07-02,0,1994
17899,787915,4376,0,1489,John Luebkemann,375,1875,0,2,501,Mark Kenas,342,1869,0,3,5,1,1994-07-02,0,1994

In [54]:
Scrab_5['winnerscore'].corr(Scrab_5['loserscore'])

-0.24900080522596177